attempting to add subfolders to download artifacts and rename macos. attempt #1

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,25 +1,18 @@
 name: Flutter CI
 
-# https://gist.github.com/youhide/121750fc4878801ea8e908080b535beb
-
-on: #push
+on:
   push:
-    #    branches: [ dev ]
     tags:
       - '*'
-#  pull_request:
-#    branches: [ dev ]
 
 env:
-  flutter_channel: "stable" # or: 'stable' or 'dev' or 'beta'
-  #flutter_version: '2.2.2'
+  flutter_channel: "stable"
   macos_path: "build/macos/Build/Products/Release/TriOS.app"
   windows_path: "build/windows/x64/runner/Release/*"
 #  linux_path: "build/linux/runner/Release/*"
 
 jobs:
   upload-release:
-
     runs-on: ubuntu-latest
     needs: [ build-macos,
       #            build-linux,
@@ -29,37 +22,23 @@ jobs:
     steps:
       - uses: actions/checkout@v3
 
-      #      - name: 'Get Previous tag'
-      #        id: previoustag
-      #        uses: "WyriHaximus/github-action-get-previous-tag@v1"
-      #        with:
-      #          fallback: 0.0.1 # Optional fallback tag to use when no tag can be found
-
-      #      - name: 'Get current time'
-      #        uses: josStorer/get-current-time@v2
-      #        id: current-time
-      #        with:
-      #          format: 'YYYYMMDD-HH'
-      #          utcOffset: "+08:00"
-
       - name: Fetch Tags
         run: git fetch --prune --unshallow --tags
 
       #         Tags starting with 0 or with unstable, dev, qa, prerelease, or rc in them will be marked as prerelease.
       - name: Set Variables
         run: |
-               echo "VERSION=$(git describe --tags)" >> $GITHUB_ENV
-               git log --format=%B -n 1 $(git log -1 --pretty=format:"%h") | cat - > changes.txt
-               prerelease_regex=".*dev|qa|rc|prerelease|unstable.*"
-               if [[ "$(git describe --tags)" =~ $prerelease_regex ]]; then
-               echo "IS_PRERELEASE=true" >> $GITHUB_ENV;
-               else
-               echo "IS_PRERELEASE=false" >> $GITHUB_ENV;
-               fi
+          echo "VERSION=$(git describe --tags)" >> $GITHUB_ENV
+          git log --format=%B -n 1 $(git log -1 --pretty=format:"%h") | cat - > changes.txt
+          prerelease_regex=".*dev|qa|rc|prerelease|unstable.*"
+          if [[ "$(git describe --tags)" =~ $prerelease_regex ]]; then
+            echo "IS_PRERELEASE=true" >> $GITHUB_ENV;
+          else
+            echo "IS_PRERELEASE=false" >> $GITHUB_ENV;
+          fi
 
       - name: 'Create GitHub release from a tag'
         id: create_release
-        #        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
         uses: ncipollo/release-action@v1
         with:
           commit: '${{ github.sha }}'
@@ -69,54 +48,23 @@ jobs:
           draft: false
           prerelease: '${{ env.IS_PRERELEASE }}'
 
-      #      - name: 'Create GitHub release from dev'
-      #        id: create_release
-      #        if: ${{ ! startsWith(github.ref, 'refs/heads/dev') }}
-      #        uses: ncipollo/release-action@v1
-      #        with:
-      #          commit: '${{ github.sha }}'
-      #          tag: '${{ steps.previoustag.outputs.tag }}-${{ steps.current-time.outputs.time }}'
-      #          name: "Build ${{ steps.previoustag.outputs.tag }}-${{ steps.current-time.outputs.time }}"
-      #          prerelease: true
-
-      #      - name: create release
-      #        id: create_release
-      #        uses: actions/create-release@master
-      #        env:
-      #          GITHUB_TOKEN: ${{ secrets.TOKEN }}
-      #        with:
-      #          tag_name: ${{ github.ref }}
-      #          release_name: Release ${{ github.ref }}
-      #          draft: false
-      #          prerelease: true
-
-      - name: download artifacts
+      - name: Download Artifacts
         uses: actions/download-artifact@v1
         with:
           name: uploads
 
-      - name: upload macos
+      - name: Upload macOS Artifact
         id: upload-macos
         uses: shogo82148/actions-upload-release-asset@v1
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           upload_url: ${{ steps.create_release.outputs.upload_url }}
-          asset_path: ./uploads/macos.zip
-          asset_name: macos.zip
+          asset_path: ./uploads/TriOS-MacOS.zip
+          asset_name: TriOS-MacOS.zip
+          asset_content_type: application/zip
 
-      #      - name: upload linux
-      #        id: upload-linux
-      #        uses: actions/upload-release-asset@v1.0.1
-      #        env:
-      #          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      #        with:
-      #          upload_url: ${{ steps.create_release.outputs.upload_url }}
-      #          asset_path: ./uploads/linux.zip
-      #          asset_name: linux.zip
-      #          asset_content_type: application/zip
-
-      - name: upload windows
+      - name: Upload Windows Artifact
         id: upload-windows
         uses: shogo82148/actions-upload-release-asset@v1
         env:
@@ -127,47 +75,79 @@ jobs:
           asset_name: TriOS-Windows.zip
           asset_content_type: application/zip
 
+  #      - name: upload linux
+  #        id: upload-linux
+  #        uses: actions/upload-release-asset@v1.0.1
+  #        env:
+  #          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #        with:
+  #          upload_url: ${{ steps.create_release.outputs.upload_url }}
+  #          asset_path: ./uploads/linux.zip
+  #          asset_name: linux.zip
+  #          asset_content_type: application/zip
+
   build-macos:
     runs-on: macos-latest
     steps:
       - uses: actions/checkout@v3
       - uses: subosito/flutter-action@v2
         with:
-          channel: $flutter_channel
+          channel: ${{ env.flutter_channel }}
           architecture: x64
           cache: true
       - run: flutter --version
       - run: flutter upgrade
       - run: flutter config --enable-macos-desktop
       - run: flutter build macos
-      - name: zip macos artifact
-        # Fix macos path
+      - name: Prepare TriOS Directory
         run: |
-          zip -yr9 macos ${{ env.macos_path }}
-      - name: upload macos artifact
+          if [ -d "${{ env.macos_path }}" ]; then
+            mkdir -p TriOS
+            mv ${{ env.macos_path }} TriOS/
+          else
+            echo "Error: macOS build path not found"
+            exit 1
+          fi
+      - name: Zip macOS Artifact
+        run: |
+          if [ -d "TriOS" ]; then
+            zip -yr9 TriOS-MacOS.zip TriOS
+          else
+            echo "Error: TriOS directory not found"
+            exit 1
+          fi
+      - name: Upload macOS Artifact
         uses: actions/upload-artifact@v1
         with:
           name: uploads
-          path: macos.zip
+          path: TriOS-MacOS.zip
 
   build-windows:
-
     runs-on: windows-latest
     steps:
       - uses: actions/checkout@v3
       - uses: subosito/flutter-action@v2
         with:
-          channel: $flutter_channel
+          channel: ${{ env.flutter_channel }}
           architecture: x64
           cache: true
       - run: flutter --version
       - run: flutter upgrade
       - run: flutter config --enable-windows-desktop
       - run: flutter build windows
-      - name: zip win artifact
+      - name: Prepare TriOS Directory
         run: |
-          powershell Compress-Archive ${{ env.windows_path }} TriOS-Windows.zip
-      - name: upload windows artifact
+          mkdir TriOS
+          move build\windows\runner\Release\* TriOS\
+      - name: Zip TriOS Directory
+        run: |
+          if (Test-Path TriOS) {
+            powershell Compress-Archive -Path TriOS -DestinationPath TriOS-Windows.zip
+          } else {
+            Write-Error "Error: TriOS directory not found"
+            exit 1
+          }
+      - name: Upload Windows Artifact
         uses: actions/upload-artifact@v1
         with:
           name: uploads
